var trieData = [
  'onion',
  'onions',
  'white onion',
  'onion rings',
  'potato',
  'potatoes',
  'potato chips',
  'lays potato',
  'banana',
  'banana',
  'raw banana',
  'green banana',
  'carrot',
  'black carrot',
  'spring onion',
  'springonion',
  'spring',
  'spring roll',
  'cabbage',
  'purple cabbage',
  'red cabbage',
  'chinese cabbage',
  'vegetables',
  'mango',
  'raw mango',
  'mangoes',
  'dasheri mango',
  'kesar mango',
  'brinjal',
  'green brinjal',
  'pudina',
  'pusina leaves',
  'paperboat pudina',
  'cucumber',
  'himalaya soap cucumber coconut soap',
];
